"""empty message

Revision ID: 32213e518faf
Revises: b02b23ff01a4
Create Date: 2025-04-29 00:01:21.783430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32213e518faf'
down_revision: Union[str, None] = 'b02b23ff01a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chat', 'visibility')
    op.alter_column('User', 'password',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.add_column('Chat', sa.Column('visibility', postgresql.ENUM('public', 'private', name='visibility_enum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
