services:
  - type: web
    name: medisense-backend
    runtime: python
    pythonVersion: "3.10"
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT