name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Copy only backend files to EC2
      run: |
        rsync -avz --exclude '.git' -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./api/ ${{ secrets.EC2_HOST }}:/home/ubuntu/api
        rsync -avz --exclude '.git' -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./requirements.txt ${{ secrets.EC2_HOST }}:/home/ubuntu/api/
        rsync -avz --exclude '.git' -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./Dockerfile ${{ secrets.EC2_HOST }}:/home/ec2/api/

    - name: SSH and deploy with Docker
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/api
          docker ps -a | grep fastapi_app || docker stop fastapi_app || true
          docker ps -a | grep fastapi_app || docker rm fastapi_app || true
          docker build -t fastapi-app .
          docker run -d --name fastapi_app -p 8000:8000 fastapi-app
        EOF